# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-10 16:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=2000, null=True)),
                ('broker', models.CharField(max_length=2000, null=True)),
                ('email', models.EmailField(max_length=1000, null=True)),
                ('member_id', models.CharField(max_length=2000, null=True)),
                ('user_name', models.CharField(max_length=2000, null=True)),
                ('user_type', models.CharField(max_length=2000, null=True)),
                ('exchange', django.contrib.postgres.fields.jsonb.JSONField(db_index=True, null=True)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('order_type', django.contrib.postgres.fields.jsonb.JSONField(db_index=True, null=True)),
                ('product', django.contrib.postgres.fields.jsonb.JSONField(db_index=True, null=True)),
                ('public_token', models.CharField(max_length=2000, null=True)),
                ('password_reset', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
